# Generated by Django 3.2.13 on 2022-06-17 07:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'Approved'), ('RE', 'Reject'), ('NP', 'Not processed'), ('NA', 'Not answered')], default='NP', max_length=2, verbose_name='Lead status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lead created date and time')),
                ('processed_at', models.DateTimeField(null=True, verbose_name='Lead processed date and time')),
                ('offer_removed', models.BooleanField(default=False, verbose_name='Offer of the lead if not exists(removed)')),
                ('contact_phone', models.CharField(default='123-123-123', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone should be entered in a 123-456-789 format', regex='\\d{3}-\\d{3}-\\d{3}')], verbose_name='Contact phone')),
                ('customer_first_name', models.CharField(max_length=25, verbose_name='Customer first name')),
                ('customer_last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer last name')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('web_name', models.CharField(max_length=30, verbose_name='Web name')),
                ('lead_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost of the lead')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created', models.DateTimeField(auto_now_add=True, verbose_name='Order created date and time')),
                ('customer_first_name', models.CharField(max_length=25, verbose_name='Customer first name')),
                ('customer_last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer last name')),
                ('status', models.CharField(choices=[('NO', 'New order'), ('IP', 'In preparation'), ('SE', 'Sent'), ('DE', 'Delivered'), ('RE', 'Return'), ('MR', 'Money received'), ('CR', 'Confirmed return'), ('CN', 'Canceled')], default='NO', max_length=30, verbose_name='Order Status')),
                ('sent_date', models.DateField(auto_now_add=True, verbose_name='Send date for the order')),
                ('order_operator_login', models.CharField(max_length=30, verbose_name='Operator login')),
                ('lead_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.lead', verbose_name='Lead FK')),
                ('order_operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator FK')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=30, verbose_name='Name of a web')),
                ('web_description', models.TextField(blank=True, null=True, verbose_name='Description of a web')),
                ('web_api_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID for API')),
                ('web_api_key', models.CharField(max_length=24, verbose_name='Key for API')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance of a web')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OP', 'Operator'), ('SM', 'Stock manager'), ('PE', 'Payments executive'), ('AD', 'Administrator'), ('TR', 'Test role')], default='TR', max_length=30, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Refered user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Product price')),
                ('product_removed_category', models.BooleanField(default=False, verbose_name='Product category if not exist (deleted)')),
                ('product_description', models.TextField(verbose_name='Description of a product')),
                ('product_image', models.FileField(upload_to='image_pics', verbose_name='Image of a product')),
                ('quantity_available', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available quantity of products')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.productcategories', verbose_name='Product category if exists')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsToWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=30, verbose_name='Web name')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount paid')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment date and time')),
                ('web_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.web', verbose_name='Web FK')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordered quantity')),
                ('ordered_product_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordered product total price')),
                ('order_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.order', verbose_name='Order FK')),
                ('product_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.product', verbose_name='Product FK')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost of a click')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='URL of a landing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.product', verbose_name='Product')),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.web', verbose_name='Web')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='offer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.offer', verbose_name='Offer FK'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.product', verbose_name='Product FK'),
        ),
        migrations.AddField(
            model_name='lead',
            name='web_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.web', verbose_name='Web FK'),
        ),
    ]
