# Generated by Django 3.2.13 on 2022-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(default=-1, verbose_name='Invoice number'),
            preserve_default=False,
        ),
    ]
