# Generated by Django 3.2.13 on 2022-06-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_FK',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='crm_app.order', verbose_name='Order referred'),
            preserve_default=False,
        ),
    ]
