# Generated by Django 3.2.13 on 2022-06-17 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_invoice_order_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='id',
        ),
        migrations.AlterField(
            model_name='web',
            name='web_api_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ID for API'),
        ),
    ]
