# Generated by Django 3.2.13 on 2022-06-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0002_auto_20220623_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstoweb',
            name='removed_user_added',
            field=models.CharField(default=None, max_length=30, verbose_name='Added by removed user (login)'),
        ),
        migrations.AddField(
            model_name='paymentstoweb',
            name='user_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by existing user (login)'),
        ),
    ]
