# Generated by Django 3.2.13 on 2022-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20220617_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance of a web'),
        ),
    ]
