# Generated by Django 3.2.13 on 2022-06-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20220624_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='operator_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.profile', verbose_name='Operator assigned'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked user'),
        ),
    ]
