# Generated by Django 3.2.13 on 2022-06-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_web_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='web_api_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID for API'),
        ),
    ]
