# Generated by Django 3.2.13 on 2022-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New order', 'NO'), ('In preparation', 'IP'), ('Sent', 'SE'), ('Delivered', 'DE'), ('Return', 'RE'), ('Money received', 'MR'), ('Confirmed return', 'CR'), ('Canceled', 'CN')], default='NO', max_length=30, verbose_name='Order Status'),
        ),
    ]
