# Generated by Django 3.2.13 on 2022-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_apartment_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Delivery apartment number'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='test', max_length=30, verbose_name='Delivery city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_house_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Delivery house number'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(default='test', max_length=30, verbose_name='Delivery street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zip_code',
            field=models.CharField(default='test_', max_length=5, verbose_name='Delivery zip code'),
            preserve_default=False,
        ),
    ]
