# Generated by Django 3.2.13 on 2022-06-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_auto_20220624_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_operator_login',
        ),
    ]
