# Generated by Django 3.2.13 on 2022-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_remove_order_order_operator_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Web activity status'),
        ),
    ]
