# Generated by Django 3.2.13 on 2022-06-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_web_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstoweb',
            name='web_name',
        ),
    ]
