# Generated by Django 3.2.13 on 2022-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_remove_paymentstoweb_web_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstoweb',
            name='removed_user_added',
        ),
    ]
