# Generated by Django 3.2.13 on 2022-06-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.product', verbose_name='Product FK'),
        ),
    ]
