# Generated by Django 3.2.13 on 2022-06-29 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_remove_lead_product_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(default=-111, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone should be entered in a 123-456-789 format', regex='\\d{3}-\\d{3}-\\d{3}')], verbose_name='Contact phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New order', 'New order'), ('In preparation', 'In preparation'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Money received', 'Money received'), ('Confirmed return', 'Confirmed return'), ('Canceled', 'Canceled')], default='New order', max_length=30, verbose_name='Order Status'),
        ),
    ]
