# Generated by Django 3.2.13 on 2022-06-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_auto_20220629_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lead_FK',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.lead', verbose_name='Lead FK'),
        ),
    ]
