# Generated by Django 3.2.13 on 2022-07-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_product_quantity_in_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
    ]
