# Generated by Django 3.2.13 on 2022-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_auto_20220712_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(default='test_last_name', max_length=25, verbose_name='Customer last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New order', 'New order'), ('In preparation', 'In preparation'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Money received', 'Money received'), ('Confirmed return', 'Confirmed return'), ('Canceled', 'Canceled')], default='New order', max_length=30, verbose_name='Order status'),
        ),
    ]
