# Generated by Django 3.2.13 on 2022-07-19 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_auto_20220712_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='ordered_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordered quantity'),
        ),
    ]
