# Generated by Django 3.2.14 on 2022-07-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_alter_orderedproduct_ordered_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['offer_id']},
        ),
        migrations.AlterModelOptions(
            name='paymentstoweb',
            options={'ordering': ['-payment_date']},
        ),
    ]
