name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install pipenv --upgrade
        pipenv install --system
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
    - name: SECRET_KEY dummy generate
      run: |
        echo "django_secret_key=topsecretvalue" >> $GITHUB_ENV
    - name: start postgres
      run: |
        sudo systemctl start postgresql
        sudo systemctl enable postgresql
    - name: Run Tests
      run: |
        export DJANGO_SETTINGS_MODULE="crm_project.settings"
        pytest crm_project/crm_app -s -v
