name: testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
#     - name: psycopg2 prerequisites
#       run: sudo apt-get install libpq-dev
    - name: Install Dependencies
      run: |
        pip install pipenv --upgrade
        pipenv install --system
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
    - name: SECRET_KEY dummy generate
      run: |
        echo "django_secret_key=topsecretvalue" >> $GITHUB_ENV
        
#     - name: start postgres
#       run: |
#         sudo systemctl start postgresql
#         sudo systemctl enable postgresql

#     - name: Run migrations
#       run: |
#         python manage.py migrate

#     - name: Run Tests
#       run: |
#         export DJANGO_SETTINGS_MODULE="crm_project.settings"
#         pytest crm_project/crm_app -s -v

    - name: Test with pytest
      env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
      run: |
          export PYTHONPATH=$PYTHONPATH:$PYTHONPATH/crm_project/
          export DJANGO_SETTINGS_MODULE=crm_project.settings
          pytest crm_project/crm_app -s -v

